Update docs in accordance with the new auto-complete-config behavior
triton-inference-server/onnxruntime_backend pull request #128
Opened 2022-07-12 21:57 UTC by tanmayv25

2022-07-12 22:58 UTC, nv-kmcgill53 requested changes

2022-07-12 22:58 UTC, nv-kmcgill53 commented on README.md
> +other value is found. Assuming server was not launched with`--disable-auto-complete-config`
> Assuming server was not launched with`--disable-auto-complete-config`

Change to: "Assuming server was not launched with `--disable-auto-complete-config`" (adding white space between the back ticks)

2022-07-12 23:01 UTC, krishung5 submitted a review, later dismissed
Other than Kyle's comment, LGTM.

2022-07-13 00:52 UTC, Tabrizian commented on README.md
>  of the model to this default value under the following conditions:
We should mention the default value of max batch size too.

2022-07-13 01:16 UTC, Tabrizian approved these changes

2022-07-13 02:57 UTC, krishung5 approved these changes

2022-07-13 17:16 UTC, nv-kmcgill53 approved these changes

2022-07-13 21:43 UTC, merged