add ragged batch support for ort backend
triton-inference-server/onnxruntime_backend pull request #39
Opened 2021-04-21 16:28 UTC by askhade

Adding ragged batch support for onnxruntime backend

2021-04-21 18:26 UTC, deadeyegoodwin requested changes

2021-04-21 18:26 UTC, deadeyegoodwin commented on src/onnxruntime.cc
> +      // The shape for the entire input patch, [total_batch_size, ...]
".. entire input batch... "

2021-04-21 18:26 UTC, deadeyegoodwin commented on src/onnxruntime.cc
> +  // Process batch input if any
Indent? Note that we have a formatting tool that you can run that should normalize all code formatting. https://github.com/triton-inference-server/server/blob/master/CONTRIBUTING.md#coding-convention

2021-04-21 19:22 UTC, GuanLuo approved these changes
The change looks good, just need to address the comments from David.

2021-04-21 21:45 UTC, askhade commented
FYI - I haven't signed the SLA yet. Waiting on CELA review.

2021-04-22 16:30 UTC, deadeyegoodwin submitted a review, later dismissed

2021-04-28 21:39 UTC, deadeyegoodwin submitted a review, later dismissed

2021-04-29 22:11 UTC, deadeyegoodwin approved these changes

2021-05-03 16:27 UTC, deadeyegoodwin approved these changes

2021-05-03 16:28 UTC, merged